#FROM pytorch/pytorch:2.1.0-cuda11.8-cudnn8-devel
FROM nvidia/cuda:11.8.0-devel-ubuntu22.04


RUN apt-get update \
    && apt-get install -y build-essential \
    && apt-get install -y wget git vim sudo 
    # \
    # && apt-get clean \
    # && rm -rf /var/lib/apt/lists/*
    


ENV CONDA_DIR /opt/conda
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-py39_23.9.0-0-Linux-x86_64.sh  -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda

ENV PATH=$CONDA_DIR/bin:$PATH
RUN conda install -y -c fvcore -c iopath -c conda-forge fvcore iopath

#=========================
RUN echo '==========================='
RUN pip install torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 --index-url https://download.pytorch.org/whl/cu118
RUN pip install torch-geometric==2.4.0
RUN pip install "git+https://github.com/facebookresearch/pytorch3d.git@2f11ddc5ee7"

RUN pip install pytorch-lightning==2.1.0 
RUN pip install usd-core==23.8  
RUN pip install sentence-transformers==2.2.2
RUN pip install qdrant-client==1.6.4 
RUN pip install python-dotenv==1.0.0
RUN pip install langchain==0.0.268
RUN pip install point-cloud-utils==0.30.0  trimesh 
RUN pip install openai==0.27.8
RUN pip install tiktoken==0.5.1
RUN pip install open3d==0.17.0

# OPEN3D 
RUN apt-get update && apt-get install -y  xorg-dev \
    libxcb-shm0  \
    libglu1-mesa-dev \
    python3-dev \
    # Filament build-from-source
    clang 

RUN apt-get update && apt-get install -y libc++-dev \
    libc++abi-dev \
    libsdl2-dev 

RUN apt-get update && apt-get install -y \
    ninja-build \
    libxi-dev \
    # ML
    libtbb-dev \
    # Headless rendering
    libosmesa6-dev 

RUN pip install hydra-core==1.3 open-clip-torch==2.23.0 transformers==4.31.0 
RUN pip install chromadb==0.4.6
RUN pip install gymnasium==0.29.1

RUN apt-get update && apt-get install  -y graphviz

RUN pip install graphviz
RUN apt-get install -y x11-apps

#RUN pip install pyvista[all]
#RUN apt-get install -y xvfb
# #RUN pip install gradio==4.1.2
# RUN /bin/sh -c "echo sss"
# RUN pip install notebook

RUN apt install -y fonts-freefont-ttf
RUN pip install jupyterlab


#=========================
# RUN python -m pip check
#=========================

RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

ARG UID
ARG GID 
RUN useradd -rm -l -s /bin/bash dkuser -G sudo -u ${UID} 
RUN groupadd -g ${GID} ugroup
USER dkuser 
WORKDIR /work 
CMD ["/bin/bash"]

#COPY requirements2.txt  /tmp/requirements.txt 
#RUN pip install  --upgrade-strategy only-if-needed -r /tmp/requirements.txt 
#RUN conda install -y pytorch3d=0.7.5=py39_cu118_pyt201 -c pytorch3d
#RUN conda install -y pyg -c pyg
