FROM yushiang-pyt-1.8

RUN apt-get clean 
RUN apt-get update

ENV PATH="/usr/local/cuda/bin/:/opt/conda/bin:${PATH}"
#ENV export TORCH_CUDA_ARCH_LIST="6.1;7.0;7.5"

RUN apt-get install libcgal-dev


WORKDIR /















