FROM yushiang-pyt-1.8

RUN apt-get clean 
RUN apt-get update

ENV PATH="/usr/local/cuda/bin/:/opt/conda/bin:${PATH}"
#ENV export TORCH_CUDA_ARCH_LIST="6.1;7.0;7.5"

# 4.11.
#RUN apt-get install libcgal-dev  -y --no-install-recommends

RUN mkdir /cgal
WORKDIR /cgal
RUN curl -sSL https://github.com/CGAL/cgal/releases/download/v5.3.1/CGAL-5.3.1.zip   -o /cgal/CGAL-5.3.1.zip \
    && unzip CGAL-5.3.1.zip -d . 

ENV export CGAL_DIR=/cgal

WORKDIR /















