FROM yushiang-pyt-1.8

RUN apt-get clean 
RUN apt-get update

ENV PATH="/usr/local/cuda/bin/:/opt/conda/bin:${PATH}"
#ENV TORCH_CUDA_ARCH_LIST="6.1;7.0;7.5"

RUN apt-get install -y  libgmp-dev libmpfr-dev  


# cmake 12 
RUN apt-get install -y software-properties-common
RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null 

# For Ubuntu Bionic Beaver (18.04)
RUN apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'

RUN apt-get update
RUN apt purge --auto-remove cmake -y 
RUN apt install -y  cmake 


RUN mkdir /cgal 
WORKDIR   /cgal 

RUN curl -sSL https://github.com/CGAL/cgal/releases/download/v5.3.1/CGAL-5.3.1-library.zip   -o /cgal/CGAL-5.3.1-library.zip \
    && unzip CGAL-5.3.1-library.zip -d /cgal/

WORKDIR /cgal/CGAL-5.3.1 
RUN mkdir build && \
    cd build && \
    cmake .. && \
    make -j 10 && \
    make install


RUN mkdir /boost 
WORKDIR   /boost 
RUN wget https://boostorg.jfrog.io/artifactory/main/release/1.66.0/source/boost_1_66_0.tar.bz2
RUN tar --bzip2 -xf /boost/boost_1_66_0.tar.bz2
WORKDIR   /boost/boost_1_66_0
RUN ./bootstrap.sh && \
    ./b2.sh install 


WORKDIR /


